name: my_cam
description: "A simple camera app for quick product photography"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  speech_to_text: ^7.3.0
  file_picker: ^10.3.6
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


